# Generated by Django 3.2.7 on 2021-09-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_alter_registration_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputdata',
            name='temperature',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
